#!/usr/bin/env python3
"""The U0-U3 coverage matrix: six domains x T0-T5 with a binding status per cell.

A cell is BOUND only when a manifest exists whose domain AND family match the
cell. BAND_ONLY means something runs at this band but for another family or a
cross-domain coordinate suite. SPECIFICATION_ONLY means nothing runs; the
specification starter named is where a bound instance would begin. Band-only is
never counted as coverage.
"""
from __future__ import annotations
import csv, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOMAINS = ["paper", "funding", "job", "code", "research", "business"]
BANDS = ["T0", "T1", "T2", "T3", "T4", "T5"]
manifests = [json.loads(p.read_text()) for p in sorted((ROOT / "manifests").glob("*.json"))]

# where a specification-only cell would begin (DLI-Bench v0.2 starter families / probe set)
SEEDS = {
    "paper": "DLI-Bench v0.2 `document` starters (20 rows); PaperAgent bands, plan §10.1",
    "funding": "agent_coordinate_probes_v0_1 `funding::T{0..4}-H{0..2}` procedures; FundingAgent bands, plan §10.2",
    "job": "agent_coordinate_probes_v0_1 `job::T{0..4}-H{0..2}` procedures; JobAgent bands, plan §10.3",
    "code": "DLI-Bench v0.2 `software` starters (42 rows)",
    "research": "DLI-Bench v0.2 `research` starters (38 rows); research-agent field benchmarks as candidate assets",
    "business": "DLI-Bench v0.2 `planning` starters (21 rows); BusinessAgent bands, plan §10.6",
}
BAND_ONLY = {  # (domain, band) -> what runs at that band for another family
    ("code", "T0"): "uab-coordinate-t0-data_analysis / document_workflow (data and document, not a code edit)",
    ("paper", "T0"): "uab-coordinate-t0-document_workflow (document workflow, not a manuscript element)",
    ("research", "T0"): "uab-coordinate-t0-data_analysis",
    ("research", "T1"): "uab-coordinate-t1-data_analysis; five research-agent field benchmarks are candidate assets, not UAB manifests",
}
rows = []
for d in DOMAINS:
    for b in BANDS:
        hits = [m for m in manifests if m["domain"] == d and m["difficulty"]["T_band"] == b]
        if hits:
            status = "GENERATOR_BOUND" if all(m["binding"]["status"] == "GENERATOR_BOUND" for m in hits) else "BOUND"
            src = "; ".join(m["task_id"] for m in hits)
            budgets = sorted({h for m in hits for h in m["human_intervention"]["budgets"]})
        elif (d, b) in BAND_ONLY:
            status, src, budgets = "BAND_ONLY", BAND_ONLY[(d, b)], []
        else:
            status, src, budgets = "SPECIFICATION_ONLY", SEEDS[d], []
        rows.append({"domain": d, "T_band": b, "binding_status": status, "source": src, "H_budgets": " ".join(budgets)})
coord = [m for m in manifests if m["domain"] == "coordinate"]
out = ROOT / "matrix"
with open(out / "uab_matrix_v0_1.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
counts = {}
for r in rows: counts[r["binding_status"]] = counts.get(r["binding_status"], 0) + 1
md = ["# UAB v0.1 coverage matrix (generated by tools/build_matrix.py)\n",
      f"Domain-band cells: {len(rows)}. " + ", ".join(f"{k}: {v}" for k, v in sorted(counts.items())) + ".",
      f"Cross-domain coordinate manifests (not counted as domain coverage): {len(coord)}.\n",
      "| domain | " + " | ".join(BANDS) + " |", "|---|" + "---|" * len(BANDS)]
abbrev = {"BOUND": "**BOUND**", "GENERATOR_BOUND": "**GEN**", "BAND_ONLY": "band-only", "SPECIFICATION_ONLY": "spec"}
for d in DOMAINS:
    md.append(f"| {d} | " + " | ".join(abbrev[next(r for r in rows if r['domain'] == d and r['T_band'] == b)["binding_status"]] for b in BANDS) + " |")
md += ["", "## Coordinate suites (cross-domain)", "", "| manifest | coordinate | band | verifier |", "|---|---|---|---|"]
for m in coord:
    md.append(f"| `{m['task_id']}` | {m['target_coordinate'][0]} | {m['difficulty']['T_band']} | {m['verifier']['type']} |")
(out / "uab_matrix_v0_1.md").write_text("\n".join(md) + "\n")
json.dump({"cells": len(rows), "counts": counts, "coordinate_manifests": len(coord)}, open(out / "summary.json", "w"), indent=1)
print(counts, "coordinate:", len(coord))
