#!/usr/bin/env python3
"""Generate Paper 2's tables from the grid and the harmonized catalogue, so paper and dataset cannot disagree.

    python3 tools/paper_tables.py dataset/ail_v0_3 ../paper2_hilbench_v02

Writes cells_table.tex (the grid summary) and methods_tables.tex (per ladder: for every level the TESTING METHOD --
intervention, procedure, verifier/metrics, control arm, gate -- and the TESTING BENCHMARK -- witness, public forms,
generator, key, retention, status)."""
from __future__ import annotations
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from hilbench import cells, laws

def tex(s):
    s = str(s)
    for a, b in [("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"), ("#", "\\#"), ("_", "\\_"), ("^GUI", "\\textsuperscript{GUI}"), ("Ω", "$\\Omega$"), ("Θ", "$\\Theta$"), ("Ψ", "$\\Psi$"), ("Φ", "$\\Phi$"), ("Δ", "$\\Delta$"), ("τ", "$\\tau$"), ("ρ", "$\\rho$"), ("μ", "$\\mu$"), ("·", "$\\cdot$"), ("¬", "$\\neg$"), ("≥", "$\\ge$"), ("≤", "$\\le$"), ("⊨", "$\\models$"), ("⟺", "$\\iff$"), ("∧", "$\\wedge$"), ("⊃", "$\\supset$"), ("≠", "$\\ne$"), ("−", "--"), ("—", "---"), ("→", "$\\to$"), ("∈", "$\\in$"), (">=", "$\\ge$"), ("<=", "$\\le$")]:
        s = s.replace(a, b)
    return s

NAMES = {"C": "Cognitive $C$", "C^GUI": "Cognitive, GUI/screen domain $C^{\\mathrm{GUI}}$", "GP": "GUI perception $GP$ (diagnostic sub-ladder)", "I": "Individual $I$", "M": "Memory $M$", "O": "Organizational $O$", "SA": "Self-awareness $SA$", "T": "Task difficulty $T$ (ordered axis of the item)", "H": "Human intervention $H$ (ordered axis of the transcript)", "DI": "Delegation frontier $DF_{h,p}$", "HG": "Harness generations $HG$", "U": "Unified level $U$"}
CUMNAME = {"hard_capability": "hard cumulative", "hard_capability_from_SA1": "hard cumulative from SA1; SA0 not retained", "cumulative_diagnostic": "cumulative diagnostic; never promotes $C$", "cumulative_frontier": "cumulative frontier across $T$ at fixed $H, p$", "ordered_axis": "ordered axis; not cumulative", "cumulative_engineering": "cumulative engineering: $HG_g = HG_{g-1} + \\Delta_g$"}

def load_catalog(ds: Path):
    cat = {}
    for l in (ds / "canonical_method_catalog.jsonl").read_text(encoding="utf-8").splitlines():
        if l.strip(): r = json.loads(l); cat[r["canonical_method"]] = r
    forms = {}
    comb = next(ds.glob("*public_dev_combined.jsonl"))
    for l in comb.read_text(encoding="utf-8").splitlines():
        if not l.strip(): continue
        r = json.loads(l); forms.setdefault((r.get("coordinate"), r.get("level")), []).append(r.get("form_id"))
    return cat, forms

def forms_for(c, forms):
    lad, lvl = c["ladder"], c["cell"]
    keys = {("C^GUI", f"C{k}^GUI"): ("C", f"C{k}") for k in range(7)}; keys[("C^GUI", "CΩ^GUI")] = ("C", "CΩ")
    co, lv = keys.get((lad, lvl), ({"C^GUI": "C", "DI": "DI", "T": "T", "H": "H"}.get(lad, lad), lvl))
    if lad == "DI": lv = "DI-surface"
    ids = forms.get((co, lv), [])
    if lad == "C^GUI": ids = [i for i in ids if "GUI" in i]
    elif lad == "C": ids = [i for i in ids if "GUI" not in i]
    return ids

def main(ds: Path, out: Path):
    cat, forms = load_catalog(ds); n = cells.counts()["total"]; N = sum(n.values())
    # ---- grid summary
    rows = []; last = None
    for c in cells.CELLS:
        if c["ladder"] != last:
            rows.append(r"\midrule\multicolumn{5}{@{}l}{\textbf{%s} --- %s}\\*" % (NAMES[c["ladder"]], CUMNAME[c["cumulative_type"]])); last = c["ladder"]
        st = {"runs": r"\textbf{runs}", "forms": "forms", "specification": "spec."}[c["status"]]
        rows.append(" & ".join([tex(c["cell"]), tex(c["construct"]), tex(c["control_arm"]), tex(c["gate"].replace("z = ", "")), st]) + r"\\")
    head = r'''% generated by tools/paper_tables.py from hilbench/cells.py -- do not edit by hand
{\scriptsize
\begin{longtable}{@{}p{1.25cm}p{6.1cm}p{3.6cm}p{2.9cm}p{0.8cm}@{}}
\caption{The cell grid: one witness per level of every ladder, with each ladder's cumulative type. Each row is a contrast (or a structural property), the control arm it must beat, and the factor gate; \textbf{runs} = generator and verifier in the package, forms = public forms and a reference scorer, spec.\ = the law is fixed and no secure executable environment exists yet. NCELLS cells: NRUNS run, NFORMS forms, NSPEC specification. The full record is \texttt{cells.jsonl}; the testing method and benchmark of every cell are in Tables~\ref{tab:m-C}--\ref{tab:m-U}.}\label{tab:grid}\\
\toprule Cell & Construct (what must hold) & Control arm & Gate & Status \\ \midrule \endfirsthead
\toprule Cell & Construct (what must hold) & Control arm & Gate & Status \\ \midrule \endhead
\midrule \multicolumn{5}{r}{\emph{continued}}\\ \endfoot
\bottomrule \endlastfoot
'''.replace("NCELLS", str(N)).replace("NRUNS", str(n["runs"])).replace("NFORMS", str(n["forms"])).replace("NSPEC", str(n["specification"]))
    (out / "cells_table.tex").write_text(head + "\n".join(rows) + "\n\\end{longtable}}\n")
    # ---- per-ladder method + benchmark tables
    parts = [r"% generated by tools/paper_tables.py -- do not edit by hand"]
    for lad in cells.LADDERS:
        cs = [c for c in cells.CELLS if c["ladder"] == lad]; rows = []
        for c in cs:
            m = cat.get(c["method"] or "", {})
            proc = m.get("procedure", []); ctrl = m.get("controls_or_ablations", []); met = m.get("primary_metrics", [])
            method = (r"\textbf{Intervention:} " + tex(m.get("experimental_intervention") or c["witness"]) +
                      (r" \textbf{Procedure:} " + tex(" $\\to$ ".join(proc)) if proc else "") +
                      r" \textbf{Verifier:} " + tex(", ".join(met) if met else "; ".join(f["symbol"] + " (" + f["locus"] + ")" for f in c["factors"])) +
                      r" \textbf{Control:} " + tex(c["control_arm"]) + (" [" + tex("; ".join(ctrl)) + "]" if ctrl else ""))
            fids = forms_for(c, forms)
            bench = (r"\textbf{Witness:} " + tex(c["witness"]) + r" \textbf{Forms:} " + (tex(", ".join(fids)) if fids else "---") +
                     r" \textbf{Generator:} " + (r"\texttt{" + tex(c["generator"]) + "}" if c["generator"] else "---") +
                     r" \textbf{Key:} " + tex(c["key"]) + (r" \textbf{Retention:} " + tex(c["retention"]) if c["retention"] else "") +
                     (r" \textbf{Prerequisite:} " + tex(c["prereq"]) if c["prereq"] not in ("K_lower", "none") else ""))
            st = {"runs": r"\textbf{runs}", "forms": "forms", "specification": "spec."}[c["status"]]
            rows.append(" & ".join([tex(c["cell"]), method, bench, tex(c["gate"].replace("z = ", "")), st]) + r"\\")
        lab = lad.replace("^GUI", "GUI")
        parts.append(r'''
{\scriptsize
\begin{longtable}{@{}p{1.1cm}p{6.6cm}p{4.5cm}p{1.9cm}p{0.7cm}@{}}
\caption{%s --- %s. For every level: the testing method (intervention, procedure, verifier, control arm) and the testing benchmark (witness, public forms in \texttt{ail\_v0\_3}, generator, key, retention). Method fields follow the canonical record of the same cell in the harmonized catalogue; the grid supplies the control arm, the factor loci and the status.}\label{tab:m-%s}\\
\toprule Level & Testing method & Testing benchmark & Gate & St. \\ \midrule \endfirsthead
\toprule Level & Testing method & Testing benchmark & Gate & St. \\ \midrule \endhead
\midrule \multicolumn{5}{r}{\emph{continued}}\\ \endfoot
\bottomrule \endlastfoot
''' % (NAMES[lad], CUMNAME[laws.CUMULATIVE[lad]], lab) + "\n".join(rows) + "\n\\end{longtable}}\n")
    (out / "methods_tables.tex").write_text("\n".join(parts))
    print("cells_table.tex + methods_tables.tex:", N, "cells;", sum(1 for c in cells.CELLS if (c["method"] or "") in cat), "with a catalogue record")

if __name__ == "__main__":
    main(Path(sys.argv[1]), Path(sys.argv[2]))
