#!/usr/bin/env python3
"""Generate Paper 2's tables from the grid and the harmonized catalogue, so paper and dataset cannot disagree.

    python3 tools/paper_tables.py dataset/ail_v0_4 ../paper2_hilbench_v02

Writes cells_table.tex (the grid summary) and methods_tables.tex (per ladder: for every level the TESTING METHOD --
intervention, procedure, verifier/metrics, control arm, gate -- and the TESTING BENCHMARK -- witness, public forms,
generator, key, retention, status)."""
from __future__ import annotations
import json, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from hilbench import cells, laws

def tex(s):
    s = str(s)
    for a, b in [("\\", "\\textbackslash{}"), ("&", "\\&"), ("%", "\\%"), ("#", "\\#"), ("_", "\\_"), ("^GUI", "\\textsuperscript{GUI}"), ("Ω", "$\\Omega$"), ("Θ", "$\\Theta$"), ("Ψ", "$\\Psi$"), ("Φ", "$\\Phi$"), ("Δ", "$\\Delta$"), ("τ", "$\\tau$"), ("ρ", "$\\rho$"), ("μ", "$\\mu$"), ("·", "$\\cdot$"), ("¬", "$\\neg$"), ("≥", "$\\ge$"), ("≤", "$\\le$"), ("⊨", "$\\models$"), ("⟺", "$\\iff$"), ("∧", "$\\wedge$"), ("⊃", "$\\supset$"), ("≠", "$\\ne$"), ("−", "--"), ("—", "---"), ("→", "$\\to$"), ("∈", "$\\in$"), (">=", "$\\ge$"), ("<=", "$\\le$")]:
        s = s.replace(a, b)
    return s

def soft(x):
    """prose with break opportunities after / and _ (identifiers inside sentences)"""
    return tex(x).replace("/", "/\\allowbreak{}").replace("\\_", "\\_\\allowbreak{}")

def brk(x):
    """typewriter text that may break after _ / : . -"""
    t = tex(x)
    for ch in ("\\_", "/", ":", ".", "-"): t = t.replace(ch, ch + "\\allowbreak{}")
    return "\\texttt{" + t + "}"

NAMES = {"C": "Cognitive $C$", "C^GUI": "Cognitive, GUI/screen domain $C^{\\mathrm{GUI}}$", "GP": "GUI perception $GP$ (diagnostic sub-ladder)", "I": "Individual $I$", "M": "Memory $M$", "O": "Organizational $O$", "SA": "Self-awareness $SA$", "T": "Task difficulty $T$ (ordered axis of the item)", "H": "Human intervention $H$ (ordered axis of the transcript)", "DI": "Delegation frontier $DF_{h,p}$", "HG": "Harness generations $HG$", "U": "Unified level $U$"}
CUMNAME = {"hard_capability": "hard cumulative", "hard_capability_from_SA1": "hard cumulative from SA1; SA0 not retained", "cumulative_diagnostic": "cumulative diagnostic; never promotes $C$", "cumulative_frontier": "cumulative frontier across $T$ at fixed $H, p$", "ordered_axis": "ordered axis; not cumulative", "cumulative_engineering": "cumulative engineering: $HG_g = HG_{g-1} + \\Delta_g$"}

def load_catalog(ds: Path):
    """The level_benchmark_matrix (v0.4): one record per (coordinate, level) with testing_benchmark, benchmark_witness,
    external_verifier and the method fields; the canonical catalogue by method id as fallback."""
    mat = {}
    mp = ds / "level_benchmark_matrix.jsonl"
    if mp.exists():
        for l in mp.read_text(encoding="utf-8").splitlines():
            if l.strip(): r = json.loads(l); mat[(r["coordinate"], r["level"])] = r
    for l in (ds / "canonical_method_catalog.jsonl").read_text(encoding="utf-8").splitlines():
        if l.strip(): r = json.loads(l); mat.setdefault(("method", r["canonical_method"]), r)
    forms = {}
    comb = next(ds.glob("*public_dev_combined.jsonl"))
    for l in comb.read_text(encoding="utf-8").splitlines():
        if not l.strip(): continue
        r = json.loads(l); forms.setdefault((r.get("coordinate"), r.get("level")), []).append(r.get("form_id"))
    return mat, forms

def record_for(c, mat):
    return mat.get(tuple(c.get("matrix") or (c["ladder"], c["cell"]))) or mat.get(("method", c["method"] or "")) or {}

def forms_for(c, forms):
    lad, lvl = c["ladder"], c["cell"]
    keys = {("C^GUI", f"C{k}^GUI"): ("C", f"C{k}") for k in range(7)}; keys[("C^GUI", "CΩ^GUI")] = ("C", "CΩ")
    co, lv = keys.get((lad, lvl), ({"C^GUI": "C", "DI": "DI", "T": "T", "H": "H"}.get(lad, lad), lvl))
    if lad == "DI": lv = "DI-surface"
    ids = forms.get((co, lv), [])
    if lad == "C^GUI": ids = [i for i in ids if "GUI" in i]
    elif lad == "C": ids = [i for i in ids if "GUI" not in i]
    return ids

GRID_HEAD = r"""% generated by tools/paper_tables.py from hilbench/cells.py -- do not edit by hand
{\scriptsize\setlength{\tabcolsep}{4pt}\renewcommand{\arraystretch}{1.15}
\begin{longtable}{@{}>{\raggedright\arraybackslash}p{1.2cm}>{\raggedright\arraybackslash}p{6.4cm}>{\raggedright\arraybackslash}p{3.9cm}>{\raggedright\arraybackslash}p{2.7cm}@{}}
\caption{The cell grid: one witness per level of every ladder, with each ladder's cumulative type. Each row is a contrast (or a structural property), the control arm it must beat, and the factor gate with the cell's status --- \textbf{runs} = generator and verifier in the package, forms = public forms and a reference scorer, spec.\ = the law is fixed and no secure executable environment exists yet. NCELLS cells: NRUNS run, NFORMS forms, NSPEC specification. The full record is \texttt{cells.jsonl}; the testing method and benchmark of every cell are the entries of \S\ref{sec:methods}.}\label{tab:grid}\\
\toprule Cell & Construct (what must hold) & Control arm & Gate; status \\ \midrule \endfirsthead
\toprule Cell & Construct (what must hold) & Control arm & Gate; status \\ \midrule \endhead
\midrule \multicolumn{4}{r}{\emph{continued}}\\ \endfoot
\bottomrule \endlastfoot
"""

METH_HEAD = r"""
{\footnotesize\setlength{\tabcolsep}{4pt}
\begin{longtable}{@{}>{\raggedright\arraybackslash}p{1.9cm}>{\raggedright\arraybackslash}p{6.6cm}>{\raggedright\arraybackslash}p{5.9cm}@{}}
\caption{%s --- %s. For every level: the testing method (intervention, procedure, verifier, control arm) and the testing benchmark (benchmark, witness, dataset in \texttt{ail\_v0\_4}, generator, key, retention). Method and benchmark fields follow the level-benchmark matrix record of the same cell (v0.4); the grid supplies the control arm, the factor loci and the status.}\label{tab:m-%s}\\
\toprule Level; status; gate & Testing method & Testing benchmark \\ \midrule \endfirsthead
\toprule Level; status; gate & Testing method & Testing benchmark \\ \midrule \endhead
\midrule \multicolumn{3}{r}{\emph{continued}}\\ \endfoot
\bottomrule \endlastfoot
"""

def main(ds: Path, out: Path):
    cat, forms = load_catalog(ds); n = cells.counts()["total"]; N = sum(n.values())
    # ---- grid summary
    rows = []; last = None
    for c in cells.CELLS:
        if c["ladder"] != last:
            rows.append("\\midrule\\multicolumn{4}{@{}l}{\\textbf{%s} --- %s}\\\\*" % (NAMES[c["ladder"]], CUMNAME[c["cumulative_type"]])); last = c["ladder"]
        st = {"runs": "\\textbf{runs}", "forms": "forms", "specification": "spec."}[c["status"]]
        gate = "$" + tex(c["gate"].replace("z = ", "")).replace("$\\neg$", "\\neg ").replace("$", "") + "$"
        rows.append(" & ".join([tex(c["cell"]), tex(c["construct"]), tex(c["control_arm"]), gate + " \\newline " + st]) + "\\\\")
    head = GRID_HEAD.replace("NCELLS", str(N)).replace("NRUNS", str(n["runs"])).replace("NFORMS", str(n["forms"])).replace("NSPEC", str(n["specification"]))
    (out / "cells_table.tex").write_text(head + "\n".join(rows) + "\n\\end{longtable}}\n")
    # ---- per-ladder method + benchmark entries (flowing text, so pages fill; a tall table row cannot split)
    parts = ["% generated by tools/paper_tables.py -- do not edit by hand", "\\begin{small}\\setlength{\\parskip}{2pt}\\raggedright"]
    I = lambda label, body: "\\textit{" + label + "} " + body
    for lad in cells.LADDERS:
        cs = [c for c in cells.CELLS if c["ladder"] == lad]; lab = lad.replace("^GUI", "GUI")
        parts.append("\\subsubsection*{%s --- %s}\\phantomsection\\label{tab:m-%s}" % (NAMES[lad], CUMNAME[laws.CUMULATIVE[lad]], lab))
        for c in cs:
            m = record_for(c, cat)
            proc = m.get("procedure", []); ctrl = m.get("controls_or_ablations", []); met = m.get("primary_metrics", [])
            method = [I("Intervention:", soft(m.get("experimental_intervention") or c["witness"]))]
            if proc: method.append(I("Procedure:", " $\\to$ ".join(soft(x) for x in proc) + "."))
            ver = (m.get("external_verifier") + " ") if m.get("external_verifier") else ""
            ver += ("Metrics: " + ", ".join(met) + ".") if met else ("Factors: " + "; ".join(f["symbol"] + " (" + f["locus"] + ")" for f in c["factors"]) + ".")
            method.append(I("Verifier:", soft(ver)))
            method.append(I("Control arm:", soft(c["control_arm"]) + (" [" + soft("; ".join(ctrl)) + "]" if ctrl else "") + "."))
            fids = forms_for(c, forms); gen = (json.loads((ds / "generated" / "INDEX.json").read_text()) if (ds / "generated" / "INDEX.json").exists() else {}).get(c["cell"], [])
            wit = m.get("benchmark_witness") if m.get("benchmark_witness") and m.get("benchmark_witness") != m.get("experimental_intervention") else c["witness"]
            bench = [I("Benchmark:", soft(m.get("testing_benchmark") or c["witness"]) + "."), I("Witness:", soft(wit) + "."),
                     I("Dataset:", (", ".join(brk(x) for x in (fids + gen)) if (fids or gen) else "---") + "."),
                     I("Generator:", (brk(c["generator"]) if c["generator"] else "---") + "."), I("Key:", tex(c["key"]) + ".")]
            if c["retention"]: bench.append(I("Retention:", tex(c["retention"]) + "."))
            if c["prereq"] not in ("K_lower", "none"): bench.append(I("Prerequisite:", tex(c["prereq"]) + "."))
            st = {"runs": "\\textbf{runs}", "forms": "forms", "specification": "specification"}[c["status"]]
            gate = "$" + tex(c["gate"].replace("z = ", "")).replace("$\\neg$", "\\neg ").replace("$", "") + "$"
            parts.append("\\medskip\\noindent\\textbf{\\normalsize " + tex(c["cell"]) + "}\\enspace " + st + "\\enspace " + gate + "\\enspace\\textit{" + tex(c["name"]) + "}\\par\\nopagebreak")
            parts.append("\\noindent\\hangindent=1.2em\\textbf{Method.} " + " ".join(method) + "\\par")
            parts.append("\\noindent\\hangindent=1.2em\\textbf{Benchmark.} " + " ".join(bench) + "\\par")
    parts.append("\\end{small}")
    (out / "methods_tables.tex").write_text("\n".join(parts))
    print("cells_table.tex + methods_tables.tex:", N, "cells;", sum(1 for c in cells.CELLS if record_for(c, cat)), "with a matrix/catalogue record")

if __name__ == "__main__":
    main(Path(sys.argv[1]), Path(sys.argv[2]))
