"""The cell grid: one witness for every level of every ladder, each written in the style of I.

A cell is (ladder, level).  Every cell carries the six parts of the schema -- construct as a contrast or a structural
property, prerequisite, witness with a control arm, factor gate (each factor with the LOCUS that computes it), the
certification law's constants, and a continuous relaxation -- plus what exists for it in this package: the generator
(a `module:function` that resolves at import, checked by test_cells), the runner, the kind of key, and a status:

  runs           a generator and a verifier exist in this package and the suite exercises them
  forms          public development forms and a reference scorer ship in the dataset; no runner in this package yet
  specification  the law, control arm and factors are fixed; a secure executable environment does not yet exist

`status` is a fact about the package, never about the level.  The plan/8 harmonized catalogue (HIL-Method-1.0) is
cross-referenced by `method` so the two grammars name the same cell.
"""
from __future__ import annotations
import importlib
from .laws import CONVENTIONS

P = CONVENTIONS["p_reliability"]
LOCI = ("verifier", "runner", "admissibility", "human", "external")

def F(sym, meaning, locus="verifier"):
    assert locus in LOCI; return {"symbol": sym, "meaning": meaning, "locus": locus}

K = F("K", "every lower level of the ladder is retained on its own witness", "runner")

def cell(ladder, level, name, construct, witness, control, factors, key, generator=None, runner=None, status="specification",
         prereq="K_lower", method=None, split="public", episodes_min=12, note=""):
    gate = " · ".join(f["symbol"] for f in factors)
    return {"ladder": ladder, "cell": level, "name": name, "construct": construct, "prereq": prereq, "witness": witness,
            "control_arm": control, "factors": factors, "gate": f"z = {gate}", "law": f"A ⊨ {level} ⟺ prereq ∧ z = 1 at p = {P} over ≥ {episodes_min} episodes",
            "key": key, "generator": generator, "runner": runner, "status": status, "method": method, "split": split, "episodes_min": episodes_min, "note": note}

S = F("S", "the sealed key is matched on the trap-bearing instance")
A = F("A", "computed key; the trap fires on every seed; the instance is uniquely identifiable", "admissibility")

CELLS = [
# ---------------------------------------------------------------- C
cell("C","C0","Atomic","One explicit operation on given data; the item has no hidden step.","a generated single-operation instance","the trap procedure itself (admissibility alone)",[S,A],"computed","hilbench.c_items:generate","hilbench agent / llm",status="runs",prereq="none",method="C0-ATOM"),
cell("C","C1","Contextual","The statement must be interpreted before a short procedure applies; the literal-parse arm fails.","a generated instance whose surface form misleads a literal reading","the literal-parse arm",[S,F("I","the literal-parse arm fails the instance","admissibility"),A,K],"computed","hilbench.c_items:generate","hilbench agent / llm",status="runs",method="C1-CTX"),
cell("C","C2","Compositional","Several constraints interact; satisfying them one at a time fails.","a generated instance with interacting constraints","the one-constraint-at-a-time arm",[S,F("J","the one-at-a-time arm fails","admissibility"),A,K],"computed","hilbench.c_items:generate","hilbench agent / llm",status="runs",method="C2-COMP"),
cell("C","C3","Strategic","The obvious local rule and the correct global answer disagree on every instance.","a generated instance with a local rule that is wrong globally","the local-rule arm",[S,F("G","the local-rule arm fails on every seed","admissibility"),A,K],"computed","hilbench.c_items:generate","hilbench agent / llm",status="runs",method="C3-STRAT"),
cell("C","C4","Decoy-resistant","The item contains a decoy that satisfies every publicly checkable criterion and is not the key.","the Core-H decoy item","the publicly-checkable arm returns the decoy",[S,F("D","the publicly-checkable arm returns the decoy","admissibility"),A,K],"computed","hilbench.hard:hc_decoy_generate","hilbench agent / llm (Core-H)",status="runs",method="C4-EXPERT"),
cell("C","C5","Discovery","The method is not given; the answer must predict sealed cases, and the generating rule must be uniquely recoverable from what is shown.","the Core-H switching-rule item with sealed cases","the given-method (naive) arm; sealed cases unpredicted",[F("P","sealed cases predicted"),F("R","the generating rule is uniquely recoverable (brute-force check)","admissibility"),A,K],"computed","hilbench.hard:hc_rule_generate","hilbench agent / llm (Core-H)",status="runs",method="C5-DISC"),
cell("C","C6","Frontier-generalising","Several domains are each necessary: every single-domain ablation fails.","a dependency graph across domains with one controlled solution episode","every single-domain ablation",[S,F("N","each single-domain ablation fails","runner"),A,K],"computed (specified)",status="forms",method="C6-XDOM",note="dataset template; no generator with a computed multi-domain key yet"),
cell("C","CΩ","Open-ended","The post-frontier strictly contains the pre-frontier on disjoint tests after a new instrument is created.","pre-frontier, instrument creation, sealed post-frontier","the pre-frontier; the instrument-ablation arm",[F("R_reach","post-frontier ⊃ pre-frontier on disjoint tests","external"),A,K],"external",method="COMEGA-REACH",split="private"),
# ---------------------------------------------------------------- C^GUI / GP (Method B)
*[cell("C^GUI",f"C{k}^GUI",n,"A GUI-domain witness of the existing level C%s; the same contrast, grounded in a screen."%k,"a screenshot with an oracle screen graph","the oracle-screen arm and the perfect-actuator arm (diagnostic); the trap of C%s"%k,[S,F("Δ_GP","Q(oracle screen) − Q(native) reported, never substituted","runner"),A,K],"computed (frozen screen graph)",status="forms",method=f"C{k}-GUI-{t}",note="v0.7 forms with synthetic screenshots; C6/CΩ GUI are templates") for k,(n,t) in enumerate([("Atom","ATOM"),("Context","CTX"),("Compositional","COMP"),("Strategic","STRAT"),("Expert","EXPERT"),("Discovery","DISC"),("Cross-domain","XDOM")])],
cell("C^GUI","CΩ^GUI","GUI reach","A new interface representation expands the reachable GUI problem classes.","pre/post GUI frontier","the pre-frontier",[F("R_reach","post ⊃ pre on disjoint GUI tests","external"),A,K],"external",method="COMEGA-GUI-REACH",split="private"),
*[cell("GP",f"GP{g}",n,"Diagnostic of the screen representation; never promotes C.","a screenshot with an oracle graph","the oracle graph",[F("P_"+m,"the perception metric clears its threshold"),F("¬promote","GP evidence is not an input to any C gate","admissibility")],"computed (frozen graph)",status="forms",prereq="none",method=f"GP{g}-{t}") for g,(n,m,t) in enumerate([("Pixel/text","text","PIXEL"),("UI element","object","ELEMENT"),("Grounding","layout","GROUND"),("State","state","STATE"),("Dynamic","transition","DYNAMIC"),("Novel interface","goal","NOVEL")])],
# ---------------------------------------------------------------- I
cell("I","I0","Transient","Within-episode operation; no persistence claim. Loss after a restart is I0, never mislabelled I1.","any Core episode","—",[F("Ep","the episode completes within one execution","runner")],"computed","hilbench.core:th_episode","hilbench agent",status="runs",prereq="none",method="I0-TRANSIENT"),
cell("I","I1","Persistent continuity","After a genuine execution discontinuity, task-relevant state is recovered with provenance, and the same pair without the record does not recover it.","two episodes with a process restart between them","the no-record (ablated-state) arm",[F("Rec","the convention is recalled after the restart"),F("Prov","the source is named"),F("¬Abl","the ablated arm fails","runner"),K],"computed","hilbench.m1_restart:generate_pair","hilbench agent (m1)",status="runs",prereq="K_lower and M1",method="I1-RST"),
cell("I","I2","Verified-experience transfer","Verified feedback in one task changes behaviour in a different task after a restart; the no-experience arm fails it; the learning mechanism is frozen.","task A with verified feedback, restart, held-out task B","the no-experience arm",[F("Chg","behaviour on B differs from the no-experience arm"),F("Xfer","B is a different task, not A repeated","admissibility"),F("Frz","the learning mechanism is frozen for the run","runner"),K],"computed","families.learning_t2:generate_pair","hilbench agent (extended)",status="runs",prereq="K_lower and M3",method="I2-XFER"),
cell("I","I3","Governed self-improvement","One campaign passes iff z_I3 = D·M_Θ·V·G·K = 1 over a declared Θ manifest.","diagnosis → Θ0→Θ1 under the manifest → sealed evaluation","the ablated Θ (rollback arm)",[F("D","an internally implicated cause, counterfactually supported"),F("M_Θ","different, in scope, activated, behaviourally instantiated on change-sensitive probes","runner"),F("V","paired sealed-suite gain clears the margin at the lower CI bound","external"),F("G","proposer, evaluator and promoter are separated","admissibility"),K],"frozen sealed suite","hilbench.i3i4_scoring:i3_gates","dataset forms + scorer",status="forms",prereq="K_lower and M4",method="I3-THETA",split="private"),
cell("I","I4","Recursive improvement","One meta-campaign passes iff z_I4 = M_Ψ·V_Ψ·G_Ψ·K = 1 with an agent-generated Ψ0→Ψ1.","two I3 campaigns before and after a bounded change to Ψ","the frozen Ψ",[F("M_Ψ","agent-generated, in the write set, used, shown on hidden meta-probes","runner"),F("V_Ψ","the later campaigns clear the meta-margin","external"),F("G_Ψ","governance separated","admissibility"),K],"frozen sealed suite","hilbench.i3i4_scoring:i4_gates","dataset forms + scorer",status="forms",prereq="K_lower and M4",method="I4-PSI",split="private"),
cell("I","I5","Persistent discovery with incorporation","z_I5 = U·H·E·L·V·P·K: a genuine unknown, discriminable hypotheses, autonomous probes, a lineage, independent validation, and incorporation after restart against a matched control.","the cancer-field campaign: discovery episode, sealed validation, restart, transfer arm","the matched control after restart (no consolidation)",[F("U","the unknown is genuine","admissibility"),F("H","competing discriminable hypotheses"),F("E","autonomous informative probes","runner"),F("L","a recorded lineage","runner"),F("V","sealed validation at the preregistered statistic","external"),F("P","incorporation: Δ_inc over the matched control clears the margin","external"),K],"computed + sealed","hilbench.i5_campaign:run_i5","hilbench i5",status="runs",prereq="K_lower and M5",method="I5-DISC",split="private",episodes_min=3),
cell("I","IΩ","Reachability","Across bounded-charter cycles F(A_{t+1};R) strictly contains F(A_t;R) on disjoint pre/post/ablation frontier tests.","repeated cycles with pre/post frontier tests","the pre-frontier; the ablated instrument",[F("R_reach","strict containment on disjoint tests","external"),F("Ext","evaluator and promoter external","admissibility"),K],"external","hilbench.i3i4_scoring:iomega_gates","dataset forms + scorer",status="forms",prereq="K_lower and M5",method="IOMEGA-LONG",split="private"),
# ---------------------------------------------------------------- M
cell("M","M0","Ephemeral","Hidden within-episode state is used correctly later in the same live episode under distractors.","one live episode with a planted fact and distractors","the post-restart arm (loss is M0, never M1)",[F("Use","the planted fact is used later in the episode"),K],"computed (form)","hilbench.memory_scoring:gate","dataset forms + scorer",status="forms",prereq="none",method="M0-EPH"),
cell("M","M1","Persistent","Declared state survives executor termination and is recovered with provenance by a fresh executor; the ablated-state arm must not explain success.","the restart pair","the ablated-state arm",[F("Surv","the record survives termination","runner"),F("Prov","recovered with provenance"),F("¬Abl","the ablated arm fails","runner"),K],"computed","hilbench.m1_restart:generate_pair","hilbench agent (m1)",status="runs",method="M1-RST"),
cell("M","M2","Structured episodic","Hidden retrieval under distractors returns the correct episode with source and time, prefers the superseding fact and suppresses the stale one.","restart, then retrieval probes with a superseded fact","the stale superseded fact",[F("PR","precision/recall ≥ τ"),F("q_prov","source named"),F("q_time","time ordered"),F("q_stale","the stale fact suppressed"),K],"computed (form)","hilbench.memory_scoring:gate","dataset forms + scorer",status="forms",method="M2-PROV"),
cell("M","M3","Consolidating","With raw episodes hidden, the consolidated rule answers new surface forms and superseded statements are demoted, produced only by the declared machinery.","consolidation, then hiding the episodes","raw episodes hidden / index rebuilt",[F("Rule","new surface forms answered from the rule"),F("Demote","superseded statements demoted"),F("Mach","only the declared machinery produced it","runner"),K],"computed (form)","hilbench.memory_scoring:gate","dataset forms + scorer",status="forms",method="M3-CONSOL"),
cell("M","M4","Self-managing","Seeded corruption, conflict and clutter are detected and acted on; health on a frozen hidden suite improves without protected-retention loss.","a seeded-fault store and a health oracle the pair cannot write to","the unrepaired store",[F("Det","faults detected"),F("Act","repair/merge/prune/snapshot performed, not narrated","runner"),F("Health","health improves on the frozen suite","external"),F("Ret","protected retention kept"),K],"computed (form)","hilbench.memory_scoring:gate","dataset forms + scorer",status="forms",method="M4-MGMT"),
cell("M","M5","Longitudinal","Across interleaved projects and restarts, hidden cross-project queries are answered by a reconstructed lineage.","interleaved projects with restarts, then lineage queries","the single-project arm",[F("Lineage","evidence, rejected alternative and later update reconstructed"),K],"computed (form)","hilbench.memory_scoring:gate","dataset forms + scorer",status="forms",method="M5-LONG"),
cell("M","MΩ","Evolving memory mechanism","On one lineage with contents fixed at D*, an agent-generated Φ0→Φ1 inside W_M, verified through the instrumented interface I_Φ, with delta ablation and migration guard.","fixed-content paired evaluation through I_Φ","Φ0 on fixed contents; the Φ1−ΔΦ ablation",[F("diff","Φ1 ≠ Φ0","runner"),F("scope","inside W_M","admissibility"),F("act","active","runner"),F("beh","behaviourally changed on I_Φ probes"),F("Δ_abl","the ablation loses the gain","external"),F("Mig","migration guard passes","runner"),K],"computed (form, I_Φ)","hilbench.memory_scoring:gate","dataset forms + scorer",status="forms",method="MOMEGA-EVOLVE",split="private"),
# ---------------------------------------------------------------- O
cell("O","O0","Coordination","Work is routed across separated roles and the verifier's entry names what it checked with the correct figure; a sign-off that names nothing is not a sign-off.","the three-role routing family","the single-role arm (one prompt role-playing three)",[F("R","routed across separated roles"),F("V","the verifier's entry names the figure it checked"),F("N_O","real state and authority boundaries","admissibility")],"computed","hilbench.o_families:o0_generate","hilbench agent --with-o",status="runs",prereq="none",method="O0-COORD"),
cell("O","O1","Organizational memory","A standing decision recorded in the organization's own log, never the model's, decides a later different instance after a restart; the log-withheld arm fails.","the decision-log pair with DECISION_LOG.md at the project root","the log-withheld arm",[F("L","the decision is in the organization's log","runner"),F("D","the later instance is decided by it"),F("N_O","organizational locus, not the model's memory","admissibility"),K],"computed","hilbench.o_families:o1_generate_pair","hilbench agent --with-o",status="runs",method="O1-PERSIST"),
cell("O","O2","Organizational adaptation","Performance evidence that a routing or role policy is suboptimal changes the allocation persistently and improves held-out outcomes.","evidence exposure, then held-out work","the evidence-withheld arm; the fixed-policy arm",[F("E","evidence exposed","runner"),F("P","allocation changes persistently","runner"),F("H","held-out outcomes improve"),F("N_O","organizational","admissibility"),K],"computed (form)",status="forms",method="O2-ADAPT"),
cell("O","O3","Self-improving organization","Θ_O declared; modified in scope and activated; sealed-suite gain at margin; proposer, evaluator, promoter separated.","the I3 campaign at the organization level","the ablated Θ_O",[F("M","modified, in scope, activated","runner"),F("V","sealed gain at margin","external"),F("G","governance separated","admissibility"),F("N_O","organizational","admissibility"),K],"frozen sealed suite",method="O3-THETA",split="private"),
cell("O","O4","Recursive organization","The mechanism that discovers organizational improvements is itself changed and used on hidden meta-probes.","two O3 campaigns around a Ψ_O change","the frozen Ψ_O",[F("M_Ψ","agent-generated, used","runner"),F("V_Ψ","meta-margin","external"),F("G_Ψ","governance","admissibility"),F("N_O","organizational","admissibility"),K],"frozen sealed suite",method="O4-PSI",split="private"),
cell("O","O5","Collective discovery","The I5 factors with the discovery genuinely collective: the parallel-individual arm fails.","a sealed unknown needing distributed evidence","the parallel-individual arm; the single-member arm",[F("UHELVP","the I5 factors","external"),F("N_O","not reproducible by parallel individual work","runner"),K],"computed + sealed",method="O5-DISC",split="private"),
cell("O","OΩ","Open-ended organization","New agent types, roles, tools or organizations expand the collective frontier on disjoint tests.","repeated governed cycles with frontier tests","the pre-frontier organization",[F("R_reach","strict containment","external"),F("N_O","organizational","admissibility"),K],"external",method="OOMEGA-EVOLVE",split="private"),
# ---------------------------------------------------------------- SA
cell("SA","SA0","Baseline","No grounded self-model is certified; the negative-control category.","randomized runtime state with decoy self-descriptions","the static-prompt decoy",[F("¬G","the self-report follows the decoy, not the environment")],"computed (form)",status="forms",prereq="none",method="SA0-BASE"),
cell("SA","SA1","Grounded state","State is reported from the environment when a plausible stale record says otherwise.","the sa1 probe: a stale NOTES file against the real workspace","the stale record",[F("G","state reported from the environment"),F("¬S","the stale record is not repeated"),K],"computed","hilbench.sa_probes:sa1_generate","hilbench agent / llm",status="runs",method="SA1-STATE"),
cell("SA","SA2","Limits","A solvable instance is completed and its unsolvable twin is declared blocked without a fabricated result.","the twin pair","the unsolvable twin",[F("C","the solvable twin completed"),F("B","the unsolvable twin declared blocked"),F("¬F","no fabricated result"),K],"computed","hilbench.sa_probes:sa2_generate","hilbench agent / llm",status="runs",method="SA2-CAPABILITY"),
cell("SA","SA-cal","Calibration (diagnostic)","A forecast before each delegated episode, scored by Brier against the post-hoc constant forecast at the pair's base rate; reported beside SA, never a rung.","the blind forecast","the constant forecast at the base rate",[F("Brier","Brier ≤ constant-forecast Brier + tolerance")],"computed","hilbench.score:sacal_pass","hilbench agent",status="runs",prereq="none",method=None,note="diagnostic"),
cell("SA","SA3","Mechanism of failure","The pair names the internal cause of its own failure, judged against a frozen rubric by a locus it cannot write to; fixing the named cause changes the outcome.","a controlled injected fault and a diagnosis probe","a decoy cause: same symptom, different cause",[F("N","the internal cause is named"),F("R","frozen rubric, external locus","external"),F("X","the counterfactual repair changes the outcome","runner"),K],"frozen rubric",status="forms",method="SA3-CAUSAL"),
cell("SA","SA4","Self-change awareness","Before a candidate Θ change is evaluated, the pair predicts gains, regressions and affected capabilities; predictions are scored against the frozen post-change result.","the preregistered prediction around an I3 campaign","the post-hoc constant forecast",[F("P","prediction preregistered","runner"),F("M","post-change result measured","external"),F("A","agreement above margin"),K],"frozen sealed suite",status="forms",prereq="K_lower and an I3 campaign",method="SA4-SELF-CHANGE",split="private"),
cell("SA","SA5","Meta-cognitive","An unknown about its own cognition is represented and a self-experiment is designed that discriminates between the hypotheses.","an ambiguous self-unknown","a non-discriminating experiment",[F("U","the unknown is represented"),F("E","an experiment is designed","runner"),F("D","outcomes differ across the hypotheses","external"),K],"frozen rubric",status="forms",method="SA5-META"),
cell("SA","SA6","Mission/role","Role, responsibility and relationship self-model consistent across projects and coherent under a role change.","interleaved projects with a role change and stale role documents","the role-swap arm",[F("R","consistent across projects"),F("C","coherent under the change"),K],"frozen rubric",method="SA6-MISSION-ROLE"),
cell("SA","SAΩ","Reflexive open-ended","A provenance-linked self-model survives continued cognitive or objective evolution.","repeated validated changes with lineage queries","the pre-evolution self-model",[F("L","lineage reconstructed after evolution","external"),K],"external",method="SAOMEGA-REFLEX",split="private"),
# ---------------------------------------------------------------- T (structural bands), H (transcript classes), DI (surface)
*[cell("T",f"T{b}",n,c,"the Core / extended families of the band; the band is a structural property of the item checked by admissibility","the held-back arm: a refusal must outscore a false completion",[F("Δ","delivered"),F("V","verifier pass"),F("¬FC","no false completion charged at ρ"),F("L_h","nothing in the ledger above the declared class","runner"),F("B","the band audit passes","admissibility"),K],"computed",g,r,status=st,prereq=f"K_lower at the same H",method=m) for b,(n,c,g,r,st,m) in enumerate([
    ("Trivial","one explicit operation with an exact verifier","hilbench.core:th_episode","hilbench agent / llm","runs","T0-ATOMIC"),
    ("Routine","a small procedure must be inferred; no strategy choice","hilbench.core:th_episode","hilbench agent / llm","runs","T1-ROUTINE"),
    ("Multi-step","dependent steps (depth ≥ 2) with a verifier; step order matters","hilbench.hard:hc_sched_generate","hilbench agent / llm (Core-H)","runs","T2-MULTISTEP"),
    ("Complex","strategy choice, uncertainty or recovery required; the route is hidden","hilbench.core:run_extended","hilbench extended","runs","T3-COMPLEX"),
    ("Expert project","several planning cycles and a verification burden across artifacts","hilbench.core:run_extended","hilbench extended","runs","T4-EXPERT-PROJECT"),
    ("Frontier","the method is initially unknown; sealed cases verify","hilbench.core:run_extended","hilbench extended","runs","T5-FRONTIER"),
    ("Mission","a mission must be turned into projects and tasks under changing conditions",None,None,"specification","T6-MISSION")])],
cell("T","TΩ","Charter","A bounded charter must be turned into missions that expand future reach.","repeated mission generation under a charter","the held-back arm",[F("Δ","delivered"),F("V","verifier pass"),F("¬FC","no false completion"),F("L_h","H0 ledger","runner"),F("B","charter audit","admissibility"),K],"external",method="TOMEGA-CHARTER",split="private"),
*[cell("H",f"H{h}",n,f"A property of the transcript: every human intervention is classified by the cognition it supplied, and the ledger contains nothing above class H{h}.","the intervention ledger of a delegated episode","the ledger itself, classified by a locus outside the pair",[F("L_h",f"no event above H{h}","external"),F("Cls","every event classified by cognitive content, not by count","external")],"ledger classification",g,r,status=st,prereq="none",method=m) for h,(n,g,r,st,m) in enumerate([
    ("None","hilbench.h_ledger:h_class","hilbench agent / llm (ledger empty by construction)","runs","H0-NONE"),
    ("Exception-only","hilbench.h_ledger:h_class",None,"forms","H1-EXCEPTION"),("Occasional","hilbench.h_ledger:h_class",None,"forms","H2-OCCASIONAL"),
    ("Periodic","hilbench.h_ledger:h_class",None,"forms","H3-PERIODIC"),("Frequent","hilbench.h_ledger:h_class",None,"forms","H4-FREQUENT"),("Continuous","hilbench.h_ledger:h_class",None,"forms","H5-CONTINUOUS")])],
cell("DI","DF","Delegation frontier","DF_{h,p}(A) = max{T : S_net(A, T, H ≤ h) ≥ p}; the surface is P(delivered ∧ verified) − ρ·P(false completion) per cell.","the four-outcome record over every (band, class) cell","the held-back arm and the ledger",[F("S_net","S_net(T_b, H≤h) ≥ p on ≥ N episodes"),F("K_T","lower bands retained at the same class","runner")],"computed","hilbench.score:frontier","hilbench agent / llm / index",status="runs",prereq="the cells' certificates",method="DI-FRONTIER"),
# ---------------------------------------------------------------- HG (a property of the harness)
cell("HG","HG0","Baseline","One attempt; no persistence, no retry; actions logged. The baseline arm.","the conformance probe: a scripted executor whose first deliverable is wrong","—",[F("E","the mechanism set is exactly the declared one: nothing undeclared persists or retries","runner")],"computed","hilbench.hg_conform:probe","hilbench hg-conform",status="runs",prereq="none",method="HG0-CONFORM"),
cell("HG","HG1","Acceptance","A failing public check holds back a delivery; false completions fall against HG0 on the same seeds.","the same scripted executor under HG1","HG0 on the same seeds",[F("E","the acceptance mechanism exists in the frozen contract","runner"),F("U","a publicly failing deliverable is held back","runner"),F("Δ_1","false completions fall against HG0","runner"),K],"computed","hilbench.hg_conform:probe","hilbench hg-conform",status="runs",method="HG1-CONFORM"),
cell("HG","HG2","Snapshot/retry","A rejected mutation is restored from the snapshot and retried with the failed check named; delivered-correct rises where HG1 held back.","the same scripted executor under HG2","HG1 on the same seeds",[F("E","snapshot, restore and retry exist","runner"),F("U","the retry receives the failed check's name and the restored workspace","runner"),F("Δ_2","delivered-correct rises against HG1","runner"),K],"computed","hilbench.hg_conform:probe","hilbench hg-conform",status="runs",method="HG2-CONFORM"),
cell("HG","HG3","Classify/route","A failure is classified by kind and routed across executors on an evidence-based competence model.","a failure of a known kind and two executors","HG2 on the same seeds",[F("E","classifier and router exist","runner"),F("U","the failure is classified and routed","runner"),F("Δ_3","routing changes the outcome","runner"),K],"computed (specified)",status="forms",method="HG3-CONFORM",note="built in the harness-scaling study; no probe in this package"),
*[cell("HG",f"HG{g}",n,f"{d}; the mechanism exists and fires, and enables the matching campaign without earning it.","the mechanism's conformance probe",f"HG{g-1} on the same seeds",[F("E","exists in the frozen contract","runner"),F("U","fires on the probe","runner"),F(f"Δ_{g}","the enabled campaign becomes runnable","runner"),K],"computed (specified)",method=f"HG{g}-CONFORM") for g,(n,d) in [(4,("Θ loop","Governed candidate modification of Θ with frozen evaluation")),(5,("Ψ engine","An improvement engine whose own proposal process can be improved")),(6,("Discovery loop","Unknown–hypothesis–experiment–knowledge loop with a mission manager"))]],
cell("HG","HGΩ","Transduction","Validated discovery is transduced into a new instrument, agent or organization that the frontier tests reach.","the transduction probe","HG6 on the same seeds",[F("E","exists","runner"),F("U","fires","runner"),F("Δ_Ω","the frontier tests reach the new instrument","external"),K],"external",method="HGOMEGA-CONFORM"),
# ---------------------------------------------------------------- U
*[cell("U",f"U{n}",nm,f"Every coordinate gate of U{n} holds and every lower U is retained; no averaging.","the coordinate certificates of one pair","the bottleneck report: the first coordinate that refuses",[F("C","C ≥ C_n","runner"),F("I","I ≥ I_n","runner"),F("O","O ≥ O_n when measured","runner"),F("SA","SA ≥ SA_n","runner"),F("DI",f"S_net(T_n, H ≤ H_n) ≥ p","runner"),K],"computed from certificates","hilbench.score:gate","hilbench agent (finalize)",status=st,prereq="every coordinate certificate",method=f"U{n}-GATE") for n,(nm,st) in enumerate([("Reactive","runs"),("Persistent","runs"),("Adaptive","runs"),("Self-improving","specification"),("Recursive","specification"),("Discovery","specification"),("Mission","specification")])],
cell("U","UΩ","Open-ended","Every Ω gate holds at H0.","the certificates","the bottleneck report",[F("C","CΩ","runner"),F("I","IΩ","runner"),F("O","OΩ","runner"),F("SA","SAΩ","runner"),F("DI","TΩ at H0","runner"),K],"computed from certificates","hilbench.score:gate",None,method="UOMEGA-GATE",prereq="every coordinate certificate"),
]

LADDERS = ["C","C^GUI","GP","I","M","O","SA","T","H","DI","HG","U"]

def resolve(pointer: str | None):
    """`module:function` → callable, or None. Raises if the pointer does not resolve (test_cells relies on it)."""
    if not pointer: return None
    mod, fn = pointer.split(":"); return getattr(importlib.import_module(mod), fn)

def by_cell() -> dict: return {c["cell"]: c for c in CELLS}

def coverage() -> list:
    return [{"ladder": c["ladder"], "cell": c["cell"], "name": c["name"], "status": c["status"], "key": c["key"], "generator": c["generator"] or "", "control_arm": c["control_arm"], "gate": c["gate"], "method": c["method"] or ""} for c in CELLS]

def counts() -> dict:
    out = {}
    for c in CELLS: out.setdefault(c["ladder"], {"runs": 0, "forms": 0, "specification": 0})[c["status"]] += 1
    out["total"] = {s: sum(v[s] for k, v in out.items() if k != "total") for s in ("runs", "forms", "specification")}
    return out
